version: '3'

services: 
  train_of_thought_be:
    container_name: train_of_thought
    image: train_of_thought:0.0.1
    build: 
      context: .
    ports:
      - "8084:8084"
    environment: 
      - EXTERNAL_PORT=8084
      - PGDATABASE=train_of_thought
      - PGUSER=admin
      - PGPASSWORD=12345
      - PGHOST=train_of_thought_db
    depends_on: 
      train_of_thought_db:
        condition: service_healthy

  train_of_thought_db: 
    container_name: train_of_thought_db
    image: "postgres:12"
    ports:
      - "40000:5432"
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=train_of_thought
    volumes:
      - train_of_thought_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d train_of_thought"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  train_of_thought_data: {}
